# ExtraTrees default hyper‑parameters

# n_estimators: 500
# max_depth: 15        # unlimited
# criterion: gini
# class_weight: balanced
# bootstrap: false
# random_state: 42



# Tuned parameters
n_estimators: 400
max_depth: 15
criterion: gini
class_weight: balanced
bootstrap: false
random_state: 42

# data:
#   csv_path: data\interim\combined_DB22_measurements_sorted_clean.csv
# eval_cv:
#   n_splits: 10
#   random_state: 42
# model:
#   name: et
#   params:
#     n_estimators: 500
#     max_depth: 15
#     criterion: gini
#     bootstrap: false