# Tuned parameters

# n_estimators: 200
# max_depth: 35
# criterion: gini
# bootstrap: true


# Tuned parameters with higher accuracy

n_estimators: 400
max_depth: 25
criterion: entropy
bootstrap: false